### PR TITLE
Add dev container setup

### PR DESCRIPTION
**Pull request by cosmojg**
This PR merges the dev container setup from the original codebase (before it was abandoned).

### CODE REVIEW

**Comment by Ricardicus** [comment]
Thanks!
There seems to be branch conflicts. Can you resolve them?

**Comment by cosmojg** [comment]
> Thanks! There seems to be branch conflicts. Can you resolve them?

Hmm, I can't see any easy way to do that through GitHub since I don't have write access to either repository. I can't even review the conflicts! I imagine the only conflict is the spelling correction in the README so it shouldn't take too long to address that if you have a few minutes to handle it.

Thank you for maintaining this fork, by the way!

**Comment by Ricardicus** [comment]
I see, I thought this PR was from your own fork.. Then it gets tricky. I don't think I can fix it.
Maybe abandon this PR, make your own merge on your own fork, then make a new PR from your fork?
Thank you for helping me maintain it!

**Comment by cosmojg** [comment]
Ooh, that should work! I'll give it a try.

**Comment by Ricardicus** [comment]
Nice, do it! 😎

**Pull request closed without merging**
